### ISSUE TITLE
[BUG] Level element in all MOPS messages causes vatSys to crash

### ISSUE THREAD

**Issue by DivineWind04** [vatACARS/plugin#73] opened 2024-06-27 16:06 UTC
**Bug Description**
When loading up a clearance MOPS with a level element, clicking the level field will cause vatSys to crash

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Go to edit any aircraft
2. Click on a MOPS with any level element. Click on level element
3. See error
4. Cry

**Expected behaviour**
A popup of some sort to select an altitude or from a dropdown or field to enter it in

**Desktop Environment (please complete the following information):**
 - OS: W10/11
 - Plugin Version: [e.g. 1.0.0]

**Comment by PlutonusDev** [comment] 2024-06-29 22:49
The cause of this issue has been identified and a fix is being implemented. This will be fixed in the next release.

**Closed** 2024-07-05 17:07 UTC
Labels: bug
